export const STARTER_MONTHLY_FIXED_PRICE = 25;
export const PRO_MONTHLY_FIXED_PRICE = 50;
export const ENTERPRISE_MONTHLY_FIXED_PRICE = 200;

export const STARTER_AVAILABLE_ORG_USERS = 1;
export const PRO_AVAILABLE_ORG_USERS = 8;
export const ENTERPRISE_AVAILABLE_ORG_USERS = 16;

export const STARTER_MONTHLY_ANALYSIS_REQUESTS = 100;
export const PRO_MONTHLY_ANALYSIS_REQUESTS = "∞"

export const PRO_ADDITIONAL_ORG_USER_COST = 5;
export const ENTERPRISE_ADDITIONAL_ORG_USER_COST = 5;
